package com.epam.bigdata.poplavkov.spark.model

case class Row(date_time: String,
               site_name: Int,
               posa_continent: Int,
               user_location_country: Int,
               user_location_region: Int,
               user_location_city: Int,
               orig_destination_distance: Option[Double],
               user_id: Int,
               is_mobile: Option[Int],
               is_package: Option[Int],
               channel: Option[Int],
               srch_ci: String,
               srch_co: String,
               srch_adults_cnt: Option[Int],
               srch_children_cnt: Option[Int],
               srch_rm_cnt: Option[Int],
               srch_destination_id: Int,
               srch_destination_type_id: Int,
               is_booking: Int,
               cnt: Option[Int],
               hotel_continent: Int,
               hotel_country: Int,
               hotel_market: Int,
               hotel_cluster: Int)
